# degradation_config_default.yaml

# Configuration for strong degradation used for generating reference views
strong_degradation:
  downscale_factor: [2.0, 2.7]       # Random factor to downscale image before upscaling again (simulates resolution loss)
  blur_kernel_size: [7, 9, 11]       # Size of Gaussian blur kernel (simulates optical blur)
  motion_blur_kernel_size: [0, 1, 3] # Size of motion blur kernel
  chromatic_aberration_shift: [0, 5] # Pixel color shift range for chromatic aberration
  chromatic_aberration_direction: [  # Possible directions for R and B channel shift
    [0, 1], [1, 0], [-1, 1], [1, -1], [-1, -1], [1, 1]
  ]
  noise_stddev: [5, 12]              # Standard deviation for Gaussian noise
  jpeg_quality: [25, 65]             # JPEG compression quality range

# Configuration for light degradation used for input views
light_degradation:
  chromatic_aberration_shift: [0, 2]
  noise_stddev: [0, 0.6]
  jpeg_quality: [95, 100]
  displacement_mean: 0               # Mean for Gaussian random displacement
  displacement_stddev: 1.2           # Standard deviation for displacement
  displacement_max_shift: 4          # Maximum pixel shift displacement
